"""002_drop_restriction

Revision ID: 723ed788711b
Revises: 94ca094991e4
Create Date: 2019-01-23 14:07:19.456849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723ed788711b'
down_revision = '94ca094991e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restriction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restriction',
    sa.Column('restriction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('restriction_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('restriction_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('restriction_id', name='restriction_pkey')
    )
    # ### end Alembic commands ###
