"""001_init

Revision ID: 94ca094991e4
Revises: 
Create Date: 2018-12-19 11:33:00.851073

"""
from alembic import context, op
from flask import current_app
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ca094991e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_name_number', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('town_city', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('restriction',
    sa.Column('restriction_id', sa.String(), nullable=False),
    sa.Column('restriction_type', sa.String(), nullable=True),
    sa.Column('restriction_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('restriction_id')
    )
    op.create_table('user',
    sa.Column('identity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('identity')
    )
    op.create_index(op.f('ix_user_email_address'), 'user', ['email_address'], unique=True)
    # ### end Alembic commands ###

    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE \"user\", \"restriction\", \"address\" TO " +
                    current_app.config.get('APP_SQL_USERNAME'))
    context.execute("GRANT USAGE ON SEQUENCE \"address_address_id_seq\" TO " +
                    current_app.config.get('APP_SQL_USERNAME'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_address'), table_name='user')
    op.drop_table('user')
    op.drop_table('restriction')
    op.drop_table('address')
    # ### end Alembic commands ###
